[toolchain]
anchor_version = "1.0.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nirvana = "BpHiA8c1NtStZiu7romfc3hEG7nzCoLYdPUm7XmdVuZS"

[programs.devnet]
nirvana = "BpHiA8c1NtStZiu7romfc3hEG7nzCoLYdPUm7XmdVuZS"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]

[hooks]
