[programs.devnet]
nirvana = "DbeNASbybfJj2h1G4FP5bR11G2tcCrqA6WVb1iYZr5m1"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"